### ISSUE TITLE
Pretty print of distribution object

### ISSUE THREAD

**Issue by dickoa** [alexpghayes/distributions#34]
Hi Alex,

I wanted to thank you for this package, it's really well designed.

I wanted to know if it's possible to change the way we print `distribution` object.
For example, for the moment, we have this behavior:

```r
> Binomial(1, 0.5)
Binomial distribution (size = 1, p = 0.5)> 
```

But I was expecting this

```r
> Binomial(1, 0.5)
Binomial distribution (size = 1, p = 0.5)
> 
```

Is it a design choice ? Can we change it ? I can work on a PR if you think it's better ?
Thanks again for your work on this.

**Comment by alexpghayes** [comment]
Yes, can do! Will need to check this for all of the distributions.

**Comment by alexpghayes** [comment]
I wasn't running into this locally, but I added newlines to the end of every print statement. Can you give printing a try and let me know if you run into more issues?

**Comment by dickoa** [comment]
Thanks @alexpghayes for looking into this.
I think the "\n", should be at the `cat` level and not inside `glue` for the expected behavior.
This should work
`cat(glue("Binomial distribution (size = {x$size}, p = {x$p})"), "\n")`
Instead of this
`cat(glue("Binomial distribution (size = {x$size}, p = {x$p})\n"))`
Thanks again
Ahmadou
