### ISSUE TITLE
distr6 package

### ISSUE THREAD

**Issue by mkuehn10** [alexpghayes/distributions#36]
I came across this today and just thought I'd share.  Not sure how similar it is to your work.

https://alan-turing-institute.github.io/distr6/

https://cran.r-project.org/web/packages/distr6/index.html

https://github.com/alan-turing-institute/distr6/

**Comment by RaphaelS1** [comment]
Hey I'm the maintainer of distr6, let me know if you want to chat!

**Comment by alexpghayes** [comment]
@RaphaelS1 I haven't forgotten about you, don't worry, just will need to come back to this at a less busy time!

**Comment by alexpghayes** [comment]
@RaphaelS1 thanks for the chat yesterday! Looking forward to seeing how both of our projects evolve!
